version: '3.11'

services:
  web: 
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/capsync_apis
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=host.docker.internal  
